/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_fhnw_ether_avion_Avion */

#ifndef _Included_ch_fhnw_ether_avion_Avion
#define _Included_ch_fhnw_ether_avion_Avion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderCreate
 * Signature: (Ljava/lang/String;ZIDIZZIZ)J
 */
JNIEXPORT jlong JNICALL Java_ch_fhnw_ether_avion_Avion_decoderCreate
  (JNIEnv *, jclass, jstring, jboolean, jint, jdouble, jint, jboolean, jboolean, jint, jboolean);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_ether_avion_Avion_decoderDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderSetRange
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_ether_avion_Avion_decoderSetRange
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderHasAudio
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_fhnw_ether_avion_Avion_decoderHasAudio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderHasVideo
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_fhnw_ether_avion_Avion_decoderHasVideo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetDuration
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetVideoFrameRate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetVideoFrameRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetVideoWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetVideoWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderGetVideoHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_fhnw_ether_avion_Avion_decoderGetVideoHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderDecodeAudio
 * Signature: (JLjava/nio/ByteBuffer;[D)I
 */
JNIEXPORT jint JNICALL Java_ch_fhnw_ether_avion_Avion_decoderDecodeAudio
  (JNIEnv *, jclass, jlong, jobject, jdoubleArray);

/*
 * Class:     ch_fhnw_ether_avion_Avion
 * Method:    decoderDecodeVideo
 * Signature: (JLjava/nio/ByteBuffer;[D)I
 */
JNIEXPORT jint JNICALL Java_ch_fhnw_ether_avion_Avion_decoderDecodeVideo
  (JNIEnv *, jclass, jlong, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
